-- Roblox GitHub Sync Plugin (Single File Version)
-- Optimized for easy installation

local HttpService = game:GetService("HttpService")
local Selection = game:GetService("Selection")
local MarketplaceService = game:GetService("MarketplaceService")

--------------------------------------------------------------------------------
-- Base64 Module
--------------------------------------------------------------------------------
local Base64 = {}
do
    local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    function Base64.encode(data)
        return ((data:gsub('.', function(x) 
            local r,b='',x:byte()
            for i=8,1,-1 do r=r..(b%2^i-b%2^(i-1)>0 and '1' or '0') end
            return r;
        end)..'0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
            if (#x < 6) then return '' end
            local c=0
            for i=1,6 do c=c+(x:sub(i,i)=='1' and 2^(6-i) or 0) end
            return b:sub(c+1,c+1)
        end)..({ '', '==', '=' })[#data%3+1])
    end

    function Base64.decode(data)
        data = string.gsub(data, '[^'..b..'=]', '')
        return (data:gsub('.', function(x)
            if (x == '=') then return '' end
            local r,f='',b:find(x)-1
            for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
            return r;
        end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
            if (#x ~= 8) then return '' end
            local c=0
            for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
            return string.char(c)
        end))
    end
end

--------------------------------------------------------------------------------
-- Serializer Module
--------------------------------------------------------------------------------
local Serializer = {}
do
    function Serializer.Serialize(scriptInstance)
        local className = scriptInstance.ClassName
        if className ~= "Script" and className ~= "LocalScript" and className ~= "ModuleScript" then
            return nil, "Invalid script type"
        end
        
        local source = scriptInstance.Source or ""
        local header = string.format("-- @ScriptType: %s\n-- @ClassName: %s\n-- Generated by Roblox GitHub Sync Plugin\n\n", className, className)
        
        return header .. source, className
    end

    function Serializer.Deserialize(content)
        if not content then return "Script", "" end
        
        local scriptType = "Script"
        local lines = string.split(content, "\n")
        local lineIndex = 1
        
        while lineIndex <= math.min(5, #lines) do
            local line = lines[lineIndex]
            if line:match("^%s*-%-%s*@ScriptType:%s*(%w+)") then
                scriptType = line:match("^%s*-%-%s*@ScriptType:%s*(%w+)")
            end
            if line:match("^%s*-%-%s*@") then
                lineIndex = lineIndex + 1
            else
                break
            end
        end
        
        while lineIndex <= #lines and lines[lineIndex]:match("^%s*$") do
            lineIndex = lineIndex + 1
        end
        
        local cleanLines = {}
        for i = lineIndex, #lines do
            table.insert(cleanLines, lines[i])
        end
        
        local cleanSource = table.concat(cleanLines, "\n")
        return scriptType, cleanSource
    end
end

--------------------------------------------------------------------------------
-- Config Module
--------------------------------------------------------------------------------
local Config = {}
do
    local TOKEN_KEY = "GitHubSync_Token"
    local REPO_KEY = "GitHubSync_Repo"
    local BRANCH_KEY = "GitHubSync_Branch"
    local AUTOSYNC_KEY = "GitHubSync_AutoSync"

    function Config.GetToken(pluginInstance)
        if not pluginInstance then return "" end
        local success, val = pcall(function() return pluginInstance:GetSetting(TOKEN_KEY) end)
        return success and (val or "") or ""
    end

    function Config.SetToken(pluginInstance, token)
        if not pluginInstance then return end
        pcall(function() pluginInstance:SetSetting(TOKEN_KEY, token) end)
    end

    function Config.GetRepo(pluginInstance)
        if not pluginInstance then return "" end
        local success, val = pcall(function() return pluginInstance:GetSetting(REPO_KEY) end)
        return success and (val or "") or ""
    end

    function Config.SetRepo(pluginInstance, repo)
        if not pluginInstance then return end
        pcall(function() pluginInstance:SetSetting(REPO_KEY, repo) end)
    end

    function Config.GetBranch(pluginInstance)
        if not pluginInstance then return "" end
        local success, val = pcall(function() return pluginInstance:GetSetting(BRANCH_KEY) end)
        return success and (val or "") or ""
    end

    function Config.SetBranch(pluginInstance, branch)
        if not pluginInstance then return end
        pcall(function() pluginInstance:SetSetting(BRANCH_KEY, branch) end)
    end

    function Config.GetAutoSync(pluginInstance)
        if not pluginInstance then return false end
        local success, val = pcall(function() return pluginInstance:GetSetting(AUTOSYNC_KEY) end)
        return success and (val == true) or false
    end

    function Config.SetAutoSync(pluginInstance, enabled)
        if not pluginInstance then return end
        pcall(function() pluginInstance:SetSetting(AUTOSYNC_KEY, enabled) end)
    end
end

--------------------------------------------------------------------------------
-- GitHubAPI Module
--------------------------------------------------------------------------------
local GitHubAPI = {}
do
    function GitHubAPI.UrlEncode(value)
        return (tostring(value):gsub("[^%w%-%._~]", function(c)
            return string.format("%%%02X", string.byte(c))
        end))
    end

    function GitHubAPI.UrlEncodePath(path)
        local parts = string.split(tostring(path), "/")
        for i, part in ipairs(parts) do
            parts[i] = GitHubAPI.UrlEncode(part)
        end
        return table.concat(parts, "/")
    end

    local function withCacheBuster(url)
        local separator = string.find(url, "?", 1, true) and "&" or "?"
        return string.format("%s%s_=%d%d", url, separator, os.time(), math.random(0, 999999))
    end

    function GitHubAPI.MakeRequest(token, url, method, body)
        local headers = {
            ["Authorization"] = "token " .. token,
            ["Accept"] = "application/vnd.github+json",
            ["X-GitHub-Api-Version"] = "2022-11-28",
            ["Content-Type"] = "application/json",
            ["Cache-Control"] = "no-cache, no-store, must-revalidate",
            ["Pragma"] = "no-cache",
            ["If-None-Match"] = ""
        }

        method = method or "GET"
        if method == "GET" then url = withCacheBuster(url) end

        local requestData = { Url = url, Method = method, Headers = headers }
        if body then requestData.Body = HttpService:JSONEncode(body) end

        local success, response = pcall(function() return HttpService:RequestAsync(requestData) end)
        if not success then return false, "HTTP Request failed: " .. tostring(response) end

        if response.Success then
            local data = nil
            pcall(function() if response.Body and response.Body ~= "" then data = HttpService:JSONDecode(response.Body) end end)
            return true, data, response.StatusCode
        else
            return false, string.format("GitHub API Error (%d): %s", response.StatusCode, response.Body or "Unknown error"), response.StatusCode
        end
    end

    function GitHubAPI.GetDefaultBranch(token, ownerRepo)
        local url = string.format("https://api.github.com/repos/%s", ownerRepo)
        local success, data = GitHubAPI.MakeRequest(token, url, "GET")
        if not success then return false, data end
        return true, data.default_branch or "main"
    end

    function GitHubAPI.GetLatestCommitSha(token, ownerRepo, branch)
        if not branch or branch == "" then
            local ok, def = GitHubAPI.GetDefaultBranch(token, ownerRepo)
            branch = ok and def or "main"
        end
        local url = string.format("https://api.github.com/repos/%s/commits/%s", ownerRepo, GitHubAPI.UrlEncode(branch))
        return GitHubAPI.MakeRequest(token, url, "GET")
    end

    function GitHubAPI.GetRepoTree(token, ownerRepo, branch)
        if not branch or branch == "" then
            local ok, def = GitHubAPI.GetDefaultBranch(token, ownerRepo)
            branch = ok and def or "main"
        end
        local refUrl = string.format("https://api.github.com/repos/%s/commits/%s", ownerRepo, GitHubAPI.UrlEncode(branch))
        local okRef, refData = GitHubAPI.MakeRequest(token, refUrl, "GET")
        local treeRef = (okRef and type(refData) == "table" and refData.sha) or GitHubAPI.UrlEncode(branch)

        local url = string.format("https://api.github.com/repos/%s/git/trees/%s?recursive=1", ownerRepo, treeRef)
        local success, data, code = GitHubAPI.MakeRequest(token, url, "GET")
        return success, data, code
    end

    function GitHubAPI.GetFileSha(token, ownerRepo, path, branch)
        local url = string.format("https://api.github.com/repos/%s/contents/%s", ownerRepo, GitHubAPI.UrlEncodePath(path))
        if branch and branch ~= "" then url = url .. "?ref=" .. GitHubAPI.UrlEncode(branch) end
        local success, data = GitHubAPI.MakeRequest(token, url, "GET")
        return (success and type(data) == "table" and data.sha) or nil
    end

    function GitHubAPI.PutFile(token, ownerRepo, path, content, message, branch)
        local url = string.format("https://api.github.com/repos/%s/contents/%s", ownerRepo, GitHubAPI.UrlEncodePath(path))
        local sha = GitHubAPI.GetFileSha(token, ownerRepo, path, branch)
        local body = {
            message = message or ("Update " .. path),
            content = Base64.encode(content)
        }
        if sha then body.sha = sha end
        if branch and branch ~= "" then body.branch = branch end
        return GitHubAPI.MakeRequest(token, url, "PUT", body)
    end

    function GitHubAPI.GetFileContent(token, ownerRepo, path, branch)
        local url = string.format("https://api.github.com/repos/%s/contents/%s", ownerRepo, GitHubAPI.UrlEncodePath(path))
        if branch and branch ~= "" then url = url .. "?ref=" .. GitHubAPI.UrlEncode(branch) end
        local success, data = GitHubAPI.MakeRequest(token, url, "GET")
        if success and type(data) == "table" and data.content then
            return true, Base64.decode(data.content), data.sha
        end
        return false, "Failed to get file content: " .. tostring(path)
    end
end

--------------------------------------------------------------------------------
-- SyncManager Module
--------------------------------------------------------------------------------
local SyncManager = {}
do
    local function getPlaceName()
        local success, info = pcall(function() return MarketplaceService:GetProductInfo(game.PlaceId) end)
        if success and info and info.Name then
            local name = info.Name:gsub("[^%w%s-_]", ""):gsub("%s+", "_")
            if name ~= "" then return name end
        end
        if game.Name and game.Name ~= "" then
            local name = game.Name:gsub("[^%w%s-_]", ""):gsub("%s+", "_")
            if name ~= "" then return name end
        end
        return "RobloxPlace"
    end

    local function getObjectPath(obj)
        local parts = {}
        local current = obj
        while current and current ~= game do
            table.insert(parts, 1, current.Name)
            current = current.Parent
        end
        return table.concat(parts, "/")
    end

    function SyncManager.Push(token, ownerRepo, customBranch, pushAll)
        if not token or token == "" or not ownerRepo or ownerRepo == "" then return false, "Config missing." end
        local toProcess = {}
        if pushAll then
            for _, s in ipairs({"Workspace", "ServerScriptService", "ReplicatedStorage", "ServerStorage", "StarterPlayer"}) do
                local success, service = pcall(function() return game:GetService(s) end)
                if success then table.insert(toProcess, service) end
            end
        else
            toProcess = Selection:Get()
        end
        if #toProcess == 0 then return false, "Nothing to push." end
        
        local branch = customBranch
        if not branch or branch == "" then
            local ok, def = GitHubAPI.GetDefaultBranch(token, ownerRepo)
            branch = ok and def or "main"
        end
        
        local placeName = getPlaceName()
        local pushedCount, errors = 0, {}
        
        local function processObject(obj)
            if obj.ClassName == "Script" or obj.ClassName == "LocalScript" or obj.ClassName == "ModuleScript" then
                local content, err = Serializer.Serialize(obj)
                if content then
                    local remotePath = string.format("%s/%s.lua", placeName, getObjectPath(obj))
                    local ok, putErr = GitHubAPI.PutFile(token, ownerRepo, remotePath, content, "Auto-Push", branch)
                    if ok then pushedCount = pushedCount + 1 else table.insert(errors, tostring(putErr)) end
                end
            elseif obj:IsA("Folder") or obj:IsA("Model") or obj:IsA("Service") then
                for _, child in ipairs(obj:GetChildren()) do processObject(child) end
            end
        end
        
        for _, item in ipairs(toProcess) do processObject(item) end
        return pushedCount > 0, string.format("Pushed %d script(s). Errors: %d", pushedCount, #errors)
    end

    function SyncManager.Pull(token, ownerRepo, customBranch)
        local selected = Selection:Get()
        local branch = customBranch
        if not branch or branch == "" then
            local ok, def = GitHubAPI.GetDefaultBranch(token, ownerRepo)
            branch = ok and def or "main"
        end
        
        local okTree, treeData = GitHubAPI.GetRepoTree(token, ownerRepo, branch)
        if not okTree then return false, "Failed to fetch tree." end
        
        local placeName = getPlaceName()
        if #selected > 0 then
            local count = 0
            for _, obj in ipairs(selected) do
                if obj.ClassName:find("Script") then
                    local remotePath = string.format("%s/%s.lua", placeName, getObjectPath(obj))
                    local ok, content = GitHubAPI.GetFileContent(token, ownerRepo, remotePath, branch)
                    if ok then
                        local _, source = Serializer.Deserialize(content)
                        obj.Source = source
                        count = count + 1
                    end
                end
            end
            return true, "Updated " .. count .. " scripts."
        else
            local count, foldersCache = 0, { ["Workspace"] = game:GetService("Workspace") }
            local prefix = placeName .. "/"
            
            local function getOrCreateFolder(pathParts)
                local currentParent, currentPathKey, startIndex = game, "", 1
                if #pathParts > 0 and pathParts[1] == placeName then startIndex = 2 end
                if #pathParts >= startIndex then
                    local sName = pathParts[startIndex]
                    local ok, service = pcall(function() return game:GetService(sName) end)
                    if ok and service then currentParent, currentPathKey, startIndex = service, sName, startIndex + 1
                    else currentParent, currentPathKey = game:GetService("Workspace"), "Workspace" end
                else currentParent, currentPathKey = game:GetService("Workspace"), "Workspace" end
                
                for i = startIndex, #pathParts - 1 do
                    local fName = pathParts[i]
                    currentPathKey = (currentPathKey == "" and "" or currentPathKey .. "/") .. fName
                    local existing = foldersCache[currentPathKey] or currentParent:FindFirstChild(fName)
                    if not existing or not existing:IsA("Folder") then
                        existing = Instance.new("Folder")
                        existing.Name, existing.Parent = fName, currentParent
                    end
                    foldersCache[currentPathKey], currentParent = existing, existing
                end
                return currentParent
            end
            
            for _, node in ipairs(treeData.tree or {}) do
                if node.type == "blob" and node.path:sub(1, #prefix) == prefix then
                    local relPath = node.path:sub(#prefix + 1)
                    local parts = string.split(relPath, "/")
                    local fileName = parts[#parts]:gsub("%.lua$", ""):gsub("%.luau$", "")
                    local parent = getOrCreateFolder(parts)
                    local ok, content = GitHubAPI.GetFileContent(token, ownerRepo, node.path, branch)
                    if ok then
                        local sType, source = Serializer.Deserialize(content)
                        local existing = parent:FindFirstChild(fileName)
                        if existing and existing.ClassName:find("Script") then existing.Source = source
                        else
                            if existing then existing:Destroy() end
                            local s = Instance.new(sType)
                            s.Name, s.Source, s.Parent = fileName, source, parent
                        end
                        count = count + 1
                    end
                end
            end
            return true, "Imported " .. count .. " files."
        end
    end
end

--------------------------------------------------------------------------------
-- UI Module
--------------------------------------------------------------------------------
local UI = {}
do
    function UI.Init(plugin)
        local toolbar = plugin:CreateToolbar("GitHub Sync")
        local settingsButton = toolbar:CreateButton("GitHubSettings", "Settings", "rbxassetid://6023426915")
        local viewerButton = toolbar:CreateButton("GitHubViewer", "Repo Viewer", "rbxassetid://6023426915")
        
        local settingsWidget = plugin:CreateDockWidgetPluginGui("GHS_Settings", DockWidgetPluginGuiInfo.new(Enum.InitialDockState.Float, false, false, 350, 250))
        settingsWidget.Title = "GitHub Sync - Settings"
        local viewerWidget = plugin:CreateDockWidgetPluginGui("GHS_Viewer", DockWidgetPluginGuiInfo.new(Enum.InitialDockState.Float, false, false, 500, 400))
        viewerWidget.Title = "GitHub Repository Viewer"
        
        -- Settings GUI
        local settingsGui = Instance.new("Frame")
        settingsGui.Size, settingsGui.BackgroundColor3, settingsGui.Parent = UDim2.new(1, 0, 1, 0), Color3.fromRGB(45, 45, 45), settingsWidget
        local list = Instance.new("UIListLayout")
        list.Padding, list.HorizontalAlignment, list.VerticalAlignment, list.Parent = UDim.new(0, 10), Enum.HorizontalAlignment.Center, Enum.VerticalAlignment.Center, settingsGui
        
        local function createInput(label, default)
            local l = Instance.new("TextLabel")
            l.Size, l.BackgroundTransparency, l.TextColor3, l.Text, l.Parent = UDim2.new(0.9, 0, 0, 20), 1, Color3.new(1,1,1), label, settingsGui
            local b = Instance.new("TextBox")
            b.Size, b.BackgroundColor3, b.TextColor3, b.Text, b.ClearTextOnFocus, b.Parent = UDim2.new(0.9, 0, 0, 30), Color3.fromRGB(60,60,60), Color3.new(1,1,1), default, false, settingsGui
            return b
        end
        
        local tokenBox = createInput("GitHub Token (PAT):", Config.GetToken(plugin))
        local repoBox = createInput("Repository (owner/repo):", Config.GetRepo(plugin))
        local branchBox = createInput("Target Branch (empty = default):", Config.GetBranch(plugin))
        
        local autoSyncBtn = Instance.new("TextButton")
        autoSyncBtn.Size, autoSyncBtn.BackgroundColor3, autoSyncBtn.TextColor3, autoSyncBtn.Parent = UDim2.new(0.9, 0, 0, 30), Config.GetAutoSync(plugin) and Color3.fromRGB(0, 180, 80) or Color3.fromRGB(80, 80, 80), Color3.new(1,1,1), settingsGui
        autoSyncBtn.Text = "Auto-Sync: " .. (Config.GetAutoSync(plugin) and "ON" or "OFF")
        autoSyncBtn.MouseButton1Click:Connect(function()
            local s = not Config.GetAutoSync(plugin)
            Config.SetAutoSync(plugin, s)
            autoSyncBtn.Text = "Auto-Sync: " .. (s and "ON" or "OFF")
            autoSyncBtn.BackgroundColor3 = s and Color3.fromRGB(0, 180, 80) or Color3.fromRGB(80, 80, 80)
        end)
        
        local save = Instance.new("TextButton")
        save.Size, save.BackgroundColor3, save.TextColor3, save.Text, save.Parent = UDim2.new(0.9, 0, 0, 35), Color3.fromRGB(0, 162, 255), Color3.new(1,1,1), "Save Settings", settingsGui
        save.MouseButton1Click:Connect(function()
            Config.SetToken(plugin, tokenBox.Text)
            Config.SetRepo(plugin, repoBox.Text)
            Config.SetBranch(plugin, branchBox.Text)
            save.Text = "Saved!"
            task.wait(1)
            save.Text = "Save Settings"
        end)
        
        -- Viewer GUI
        local viewerGui = Instance.new("Frame")
        viewerGui.Size, viewerGui.BackgroundColor3, viewerGui.Parent = UDim2.new(1,0,1,0), Color3.fromRGB(40,40,40), viewerWidget
        local top = Instance.new("Frame")
        top.Size, top.BackgroundColor3, top.BorderSizePixel, top.Parent = UDim2.new(1,0,0,78), Color3.fromRGB(50,50,50), 0, viewerGui
        
        local function createBtn(txt, pos, color)
            local b = Instance.new("TextButton")
            b.Text, b.Size, b.Position, b.BackgroundColor3, b.TextColor3, b.Parent = txt, UDim2.new(0, 90, 0, 30), pos, color, Color3.new(1,1,1), top
            return b
        end
        
        local refreshB = createBtn("Refresh", UDim2.new(0, 10, 0, 6), Color3.fromRGB(0, 162, 255))
        local pushB = createBtn("Push", UDim2.new(0, 10, 0, 42), Color3.fromRGB(0, 140, 90))
        local pullB = createBtn("Pull All", UDim2.new(0, 110, 0, 42), Color3.fromRGB(200, 130, 40))
        
        local status = Instance.new("TextLabel")
        status.Size, status.Position, status.BackgroundTransparency, status.TextColor3, status.Text, status.TextXAlignment, status.Parent = UDim2.new(1, -130, 0, 30), UDim2.new(0, 120, 0, 6), 1, Color3.new(0.8,0.8,0.8), "Ready", Enum.TextXAlignment.Left, top

        local scroller = Instance.new("ScrollingFrame")
        scroller.Size, scroller.Position, scroller.BackgroundTransparency, scroller.CanvasSize, scroller.AutomaticCanvasSize, scroller.Parent = UDim2.new(1, 0, 1, -78), UDim2.new(0, 0, 0, 78), 1, UDim2.new(0, 0, 0, 0), Enum.AutomaticSize.Y, viewerGui
        local layout = Instance.new("UIListLayout")
        layout.Padding, layout.Parent = UDim.new(0, 4), scroller

        local function refreshViewer()
            local token, repo = Config.GetToken(plugin), Config.GetRepo(plugin)
            if token == "" or repo == "" then status.Text = "Config missing!" return end
            status.Text = "Fetching tree..."
            for _, c in ipairs(scroller:GetChildren()) do if c:IsA("TextLabel") then c:Destroy() end end
            
            local branch = Config.GetBranch(plugin)
            if branch == "" then 
                local ok, def = GitHubAPI.GetDefaultBranch(token, repo)
                branch = ok and def or "main"
            end
            
            local ok, treeData = GitHubAPI.GetRepoTree(token, repo, branch)
            if ok and treeData and treeData.tree then
                local count = 0
                for _, node in ipairs(treeData.tree) do
                    if node.type == "blob" then
                        count = count + 1
                        local l = Instance.new("TextLabel")
                        l.Size, l.BackgroundTransparency, l.TextColor3, l.Text, l.TextXAlignment, l.Parent = UDim2.new(1, -20, 0, 20), 1, Color3.new(0.9,0.9,0.9), "  " .. node.path, Enum.TextXAlignment.Left, scroller
                    end
                end
                status.Text = string.format("Loaded %d files (%s)", count, branch)
            else
                status.Text = "Fetch failed!"
            end
        end

        refreshB.MouseButton1Click:Connect(refreshViewer)
        
        pushB.MouseButton1Click:Connect(function()
            status.Text = "Pushing..."
            local ok, msg = SyncManager.Push(Config.GetToken(plugin), Config.GetRepo(plugin), Config.GetBranch(plugin))
            status.Text = msg
            if ok then refreshViewer() end
        end)
        
        pullB.MouseButton1Click:Connect(function()
            status.Text = "Pulling..."
            local ok, msg = SyncManager.Pull(Config.GetToken(plugin), Config.GetRepo(plugin), Config.GetBranch(plugin))
            status.Text = msg
        end)
        
        settingsButton.Click:Connect(function() settingsWidget.Enabled = not settingsWidget.Enabled end)
        viewerButton.Click:Connect(function() 
            viewerWidget.Enabled = not viewerWidget.Enabled 
            if viewerWidget.Enabled then refreshViewer() end
        end)
    end
end

--------------------------------------------------------------------------------
-- Main Entry Point
--------------------------------------------------------------------------------
if plugin then
    UI.Init(plugin)

    -- Auto-Sync Loop
    task.spawn(function()
        local lastSha = nil
        while true do
            local enabled = Config.GetAutoSync(plugin)
            local token, repo = Config.GetToken(plugin), Config.GetRepo(plugin)
            if enabled and token ~= "" and repo ~= "" then
                local branch = Config.GetBranch(plugin)
                if branch == "" then 
                    local ok, def = GitHubAPI.GetDefaultBranch(token, repo)
                    branch = ok and def or "main"
                end
                
                if not lastSha then
                    print("[GitHubSync] Initial Auto-Push...")
                    SyncManager.Push(token, repo, branch, true)
                end
                
                local okC, commit = GitHubAPI.GetLatestCommitSha(token, repo, branch)
                if okC and commit and commit.sha then
                    if lastSha and commit.sha ~= lastSha then
                        print("[GitHubSync] Remote changes detected, pulling...")
                        SyncManager.Pull(token, repo, branch)
                    end
                    lastSha = commit.sha
                end
            end
            task.wait(60)
        end
    end)
    print("[GitHubSync] Plugin initialized (Single File).")
end
