-- ============================================================================
-- Roblox GitHub Sync Plugin (All-in-One Single File Version)
-- Copy this entire script into a Script or ModuleScript in Roblox Studio
-- or use with Rojo / init.server.lua
-- ============================================================================

local pluginInstance = plugin
if not pluginInstance then
    return
end

local HttpService = game:GetService("HttpService")
local Selection = game:GetService("Selection")
local Workspace = game:GetService("Workspace")
local MarketplaceService = game:GetService("MarketplaceService")

-- ============================================================================
-- 1. Base64 Encoder / Decoder
-- ============================================================================
local Base64 = {}
local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

function Base64.encode(data)
    return ((data:gsub('.', function(x) 
        local r,b='',x:byte()
        for i=8,1,-1 do r=r..(b%2^i-b%2^(i-1)>0 and '1' or '0') end
        return r;
    end)..'0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
        if (#x < 6) then return '' end
        local c=0
        for i=1,6 do c=c+(x:sub(i,i)=='1' and 2^(6-i) or 0) end
        return b:sub(c+1,c+1)
    end)..({ '', '==', '=' })[#data%3+1])
end

function Base64.decode(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',b:find(x)-1
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

-- ============================================================================
-- 2. Configuration Manager
-- ============================================================================
local Config = {}
local TOKEN_KEY = "GitHubSync_Token"
local REPO_KEY = "GitHubSync_Repo"

function Config.GetToken(plugin)
    local success, val = pcall(function()
        return plugin:GetSetting(TOKEN_KEY)
    end)
    return success and (val or "") or ""
end

function Config.SetToken(plugin, token)
    pcall(function()
        plugin:SetSetting(TOKEN_KEY, token)
    end)
end

function Config.GetRepo(plugin)
    local success, val = pcall(function()
        return plugin:GetSetting(REPO_KEY)
    end)
    return success and (val or "") or ""
end

function Config.SetRepo(plugin, repo)
    pcall(function()
        plugin:SetSetting(REPO_KEY, repo)
    end)
end

-- ============================================================================
-- 3. Script Serializer (Metadata handling)
-- ============================================================================
local Serializer = {}

function Serializer.Serialize(scriptInstance)
    local className = scriptInstance.ClassName
    if className ~= "Script" and className ~= "LocalScript" and className ~= "ModuleScript" then
        return nil, "Invalid script type: " .. tostring(className)
    end
    
    local source = scriptInstance.Source or ""
    local header = string.format("-- @ScriptType: %s\n-- @ClassName: %s\n-- Generated by Roblox GitHub Sync Plugin\n\n", className, className)
    
    return header .. source, className
end

function Serializer.Deserialize(content)
    if not content then return "Script", "" end
    
    local scriptType = "Script"
    local lines = string.split(content, "\n")
    local lineIndex = 1
    
    while lineIndex <= math.min(5, #lines) do
        local line = lines[lineIndex]
        if line:match("^%s*-%-%s*@ScriptType:%s*(%w+)") then
            scriptType = line:match("^%s*-%-%s*@ScriptType:%s*(%w+)")
        end
        if line:match("^%s*-%-%s*@") then
            lineIndex = lineIndex + 1
        else
            break
        end
    end
    
    while lineIndex <= #lines and lines[lineIndex]:match("^%s*$") do
        lineIndex = lineIndex + 1
    end
    
    local cleanLines = {}
    for i = lineIndex, #lines do
        table.insert(cleanLines, lines[i])
    end
    
    local cleanSource = table.concat(cleanLines, "\n")
    return scriptType, cleanSource
end

-- ============================================================================
-- 4. GitHub API Client
-- ============================================================================
local GitHubAPI = {}

function GitHubAPI.MakeRequest(token, url, method, body)
    local headers = {
        ["Authorization"] = "token " .. token,
        ["Accept"] = "application/vnd.github+json",
        ["X-GitHub-Api-Version"] = "2022-11-28",
        ["Content-Type"] = "application/json"
    }
    
    local requestData = {
        Url = url,
        Method = method or "GET",
        Headers = headers
    }
    
    if body then
        requestData.Body = HttpService:JSONEncode(body)
    end
    
    local success, response = pcall(function()
        return HttpService:RequestAsync(requestData)
    end)
    
    if not success then
        local err = "HTTP Request failed: " .. tostring(response)
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    
    if response.Success then
        local data = nil
        pcall(function()
            if response.Body and response.Body ~= "" then
                data = HttpService:JSONDecode(response.Body)
            end
        end)
        return true, data, response.StatusCode
    else
        local err = string.format("GitHub API Error (%d): %s", response.StatusCode, response.Body or "Unknown error")
        warn("[GitHubSync Error] " .. err)
        return false, err, response.StatusCode
    end
end

function GitHubAPI.GetDefaultBranch(token, ownerRepo)
    local url = string.format("https://api.github.com/repos/%s", ownerRepo)
    local success, data, code = GitHubAPI.MakeRequest(token, url, "GET")
    if not success then
        return false, data
    end
    return true, data.default_branch or "main"
end

function GitHubAPI.GetRepoTree(token, ownerRepo, branch)
    local url = string.format("https://api.github.com/repos/%s/git/trees/%s?recursive=1", ownerRepo, branch)
    return GitHubAPI.MakeRequest(token, url, "GET")
end

function GitHubAPI.GetFileSha(token, ownerRepo, path)
    local url = string.format("https://api.github.com/repos/%s/contents/%s", ownerRepo, path)
    local success, data = GitHubAPI.MakeRequest(token, url, "GET")
    if success and type(data) == "table" and data.sha then
        return data.sha
    end
    return nil
end

function GitHubAPI.PutFile(token, ownerRepo, path, content, message)
    local url = string.format("https://api.github.com/repos/%s/contents/%s", ownerRepo, path)
    local sha = GitHubAPI.GetFileSha(token, ownerRepo, path)
    
    local encodedContent = Base64.encode(content)
    local body = {
        message = message or ("Update " .. path),
        content = encodedContent
    }
    if sha then
        body.sha = sha
    end
    
    return GitHubAPI.MakeRequest(token, url, "PUT", body)
end

function GitHubAPI.GetFileContent(token, ownerRepo, path)
    local url = string.format("https://api.github.com/repos/%s/contents/%s", ownerRepo, path)
    local success, data = GitHubAPI.MakeRequest(token, url, "GET")
    if success and type(data) == "table" and data.content then
        local decoded = Base64.decode(data.content)
        return true, decoded, data.sha
    end
    local err = "Failed to get file content or file not found: " .. path
    warn("[GitHubSync Error] " .. err)
    return false, err
end

-- ============================================================================
-- 5. Sync Manager (Push & Pull)
-- ============================================================================
local SyncManager = {}

local function getPlaceName()
    local success, info = pcall(function()
        return MarketplaceService:GetProductInfo(game.PlaceId)
    end)
    if success and info and info.Name then
        local name = info.Name:gsub("[^%w%s-_]", ""):gsub("%s+", "_")
        if name ~= "" then return name end
    end
    if game.Name and game.Name ~= "" then
        local name = game.Name:gsub("[^%w%s-_]", ""):gsub("%s+", "_")
        if name ~= "" then return name end
    end
    return "RobloxPlace"
end

local function getObjectPath(obj)
    local parts = {}
    local current = obj
    while current and current ~= game do
        table.insert(parts, 1, current.Name)
        current = current.Parent
    end
    return table.concat(parts, "/")
end

function SyncManager.Push(token, ownerRepo)
    if not token or token == "" then
        local err = "GitHub Token is not set in settings."
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    if not ownerRepo or ownerRepo == "" then
        local err = "Repository path (owner/repo) is not set in settings."
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    
    local selected = Selection:Get()
    if #selected == 0 then
        local err = "No scripts or objects selected in Roblox Studio. Please select scripts or parent folders (holding Ctrl)."
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    
    local successBranch, branchOrErr = GitHubAPI.GetDefaultBranch(token, ownerRepo)
    local branch = successBranch and branchOrErr or "main"
    
    local placeName = getPlaceName()
    local pushedCount = 0
    local errors = {}
    
    local function processObject(obj)
        local className = obj.ClassName
        if className == "Script" or className == "LocalScript" or className == "ModuleScript" then
            local fileContent, err = Serializer.Serialize(obj)
            if fileContent then
                local objPath = getObjectPath(obj)
                local remotePath = string.format("%s/%s.lua", placeName, objPath)
                local msg = string.format("Push %s (%s)", obj.Name, className)
                
                local successPut, putErr = GitHubAPI.PutFile(token, ownerRepo, remotePath, fileContent, msg)
                if successPut then
                    pushedCount = pushedCount + 1
                else
                    table.insert(errors, string.format("%s: %s", objPath, tostring(putErr)))
                end
            else
                table.insert(errors, string.format("%s: %s", obj.Name, tostring(err)))
            end
        elseif obj:IsA("Folder") or obj:IsA("Model") or obj:IsA("Workspace") or obj:IsA("DataModelHolder") then
            for _, child in ipairs(obj:GetChildren()) do
                processObject(child)
            end
        end
    end
    
    for _, item in ipairs(selected) do
        processObject(item)
    end
    
    if pushedCount == 0 and #errors > 0 then
        local fullErr = "Push failed:\n" .. table.concat(errors, "\n")
        warn("[GitHubSync Error] " .. fullErr)
        return false, fullErr
    elseif #errors > 0 then
        local fullErr = "Pushed with errors:\n" .. table.concat(errors, "\n")
        warn("[GitHubSync Warning] " .. fullErr)
        return true, string.format("Pushed %d script(s) with %d error(s). Check console.", pushedCount, #errors)
    else
        print(string.format("[GitHubSync] Successfully pushed %d script(s) to %s/%s!", pushedCount, ownerRepo, placeName))
        return true, string.format("Successfully pushed %d script(s)!", pushedCount)
    end
end

function SyncManager.Pull(token, ownerRepo)
    if not token or token == "" then
        local err = "GitHub Token is not set in settings."
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    if not ownerRepo or ownerRepo == "" then
        local err = "Repository path (owner/repo) is not set in settings."
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    
    local selected = Selection:Get()
    
    local successBranch, branchOrErr = GitHubAPI.GetDefaultBranch(token, ownerRepo)
    local branch = successBranch and branchOrErr or "main"
    
    local successTree, treeData = GitHubAPI.GetRepoTree(token, ownerRepo, branch)
    if not successTree or not treeData or not treeData.tree then
        local err = "Failed to fetch repository tree: " .. tostring(treeData)
        warn("[GitHubSync Error] " .. err)
        return false, err
    end
    
    local placeName = getPlaceName()
    
    if #selected > 0 then
        local updatedCount = 0
        local errors = {}
        
        for _, selObj in ipairs(selected) do
            if selObj.ClassName == "Script" or selObj.ClassName == "LocalScript" or selObj.ClassName == "ModuleScript" then
                local objPath = getObjectPath(selObj)
                local remotePath = string.format("%s/%s.lua", placeName, objPath)
                
                local successContent, content = GitHubAPI.GetFileContent(token, ownerRepo, remotePath)
                if successContent then
                    local _, cleanSource = Serializer.Deserialize(content)
                    selObj.Source = cleanSource
                    updatedCount = updatedCount + 1
                else
                    local found = false
                    for _, node in ipairs(treeData.tree) do
                        if node.type == "blob" and (node.path:match("/" + selObj.Name + "%.lua$") or node.path:match("/" + selObj.Name + "%.luau$")) then
                            local sCont, cnt = GitHubAPI.GetFileContent(token, ownerRepo, node.path)
                            if sCont then
                                local _, cleanSource = Serializer.Deserialize(cnt)
                                selObj.Source = cleanSource
                                found = true
                                updatedCount = updatedCount + 1
                                break
                            end
                        end
                    end
                    if not found then
                        table.insert(errors, string.format("Could not find remote file for %s", selObj.Name))
                    end
                end
            end
        end
        
        if updatedCount == 0 and #errors > 0 then
            local fullErr = "Selective Pull failed:\n" .. table.concat(errors, "\n")
            warn("[GitHubSync Error] " .. fullErr)
            return false, fullErr
        else
            print(string.format("[GitHubSync] Successfully updated %d script(s) via Selective Pull.", updatedCount))
            return true, string.format("Successfully updated %d script(s).", updatedCount)
        end
    else
        local importedCount = 0
        local errors = {}
        
        local prefix = placeName .. "/"
        local foldersCache = {
            ["Workspace"] = Workspace
        }
        
        local function getOrCreateFolder(pathParts)
            local currentParent = Workspace
            local currentPathKey = "Workspace"
            
            local startIndex = 1
            if #pathParts > 0 and pathParts[1] == placeName then
                startIndex = 2
            end
            
            if #pathParts >= startIndex then
                local serviceName = pathParts[startIndex]
                if serviceName == "Workspace" then
                    startIndex = startIndex + 1
                elseif serviceName == "ServerScriptService" or serviceName == "ReplicatedStorage" or serviceName == "ServerStorage" or serviceName == "StarterPlayer" then
                    local serviceFolder = Workspace:FindFirstChild(serviceName)
                    if not serviceFolder then
                        serviceFolder = Instance.new("Folder")
                        serviceFolder.Name = serviceName
                        serviceFolder.Parent = Workspace
                    end
                    currentParent = serviceFolder
                    currentPathKey = "Workspace/" .. serviceName
                    startIndex = startIndex + 1
                end
            end
            
            for i = startIndex, #pathParts - 1 do
                local folderName = pathParts[i]
                currentPathKey = currentPathKey .. "/" .. folderName
                local existing = foldersCache[currentPathKey]
                if not existing then
                    existing = currentParent:FindFirstChild(folderName)
                    if not existing or not existing:IsA("Folder") then
                        existing = Instance.new("Folder")
                        existing.Name = folderName
                        existing.Parent = currentParent
                    end
                    foldersCache[currentPathKey] = existing
                end
                currentParent = existing
            end
            
            return currentParent
        end
        
        for _, node in ipairs(treeData.tree) do
            if node.type == "blob" and node.path:sub(1, #prefix) == prefix then
                local relPath = node.path:sub(#prefix + 1)
                local parts = string.split(relPath, "/")
                
                if #parts > 0 then
                    local fileNameWithExt = parts[#parts]
                    local fileName = fileNameWithExt:gsub("%.lua$", ""):gsub("%.luau$", "")
                    
                    local parentFolder = getOrCreateFolder(parts)
                    
                    local successContent, content = GitHubAPI.GetFileContent(token, ownerRepo, node.path)
                    if successContent then
                        local scriptType, cleanSource = Serializer.Deserialize(content)
                        
                        local existingScript = parentFolder:FindFirstChild(fileName)
                        if existingScript and (existingScript.ClassName == "Script" or existingScript.ClassName == "LocalScript" or existingScript.ClassName == "ModuleScript") then
                            existingScript.Source = cleanSource
                        else
                            if existingScript then
                                existingScript:Destroy()
                            end
                            local newScript = Instance.new(scriptType)
                            newScript.Name = fileName
                            newScript.Source = cleanSource
                            newScript.Parent = parentFolder
                        end
                        importedCount = importedCount + 1
                    else
                        table.insert(errors, "Failed to download " .. node.path)
                    end
                end
            end
        end
        
        if importedCount == 0 and #errors > 0 then
            local fullErr = "Safe Pull failed:\n" .. table.concat(errors, "\n")
            warn("[GitHubSync Error] " .. fullErr)
            return false, fullErr
        else
            print(string.format("[GitHubSync] Successfully pulled and imported %d file(s) into Workspace!", importedCount))
            return true, string.format("Successfully pulled %d file(s)!", importedCount)
        end
    end
end

-- ============================================================================
-- 6. UI Implementation
-- ============================================================================
local toolbar = pluginInstance:CreateToolbar("GitHub Sync")

local pushButton = toolbar:CreateButton("GitHubPush", "Push scripts to GitHub", "rbxassetid://6023426915", "Push")
local pullButton = toolbar:CreateButton("GitHubPull", "Pull scripts from GitHub", "rbxassetid://6023426915", "Pull")
local settingsButton = toolbar:CreateButton("GitHubSettings", "GitHub Settings", "rbxassetid://6023426915", "Settings")
local viewerButton = toolbar:CreateButton("GitHubViewer", "Repository Viewer", "rbxassetid://6023426915", "Repo Viewer")

local settingsWidgetInfo = DockWidgetPluginGuiInfo.new(
    Enum.InitialDockState.Float,
    false,
    false,
    350, 200,
    300, 150
)
local settingsWidget = pluginInstance:CreateDockWidgetPluginGui("GitHubSyncSettings", settingsWidgetInfo)
settingsWidget.Title = "GitHub Sync - Settings"

local viewerWidgetInfo = DockWidgetPluginGuiInfo.new(
    Enum.InitialDockState.Float,
    false,
    false,
    500, 400,
    400, 300
)
local viewerWidget = pluginInstance:CreateDockWidgetPluginGui("GitHubSyncViewer", viewerWidgetInfo)
viewerWidget.Title = "GitHub Repository Viewer"

-- Settings GUI
local settingsGui = Instance.new("Frame")
settingsGui.Size = UDim2.new(1, 0, 1, 0)
settingsGui.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
settingsGui.Parent = settingsWidget

local listLayout = Instance.new("UIListLayout")
listLayout.Padding = UDim.new(0, 10)
listLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
listLayout.VerticalAlignment = Enum.VerticalAlignment.Center
listLayout.Parent = settingsGui

local tokenLabel = Instance.new("TextLabel")
tokenLabel.Size = UDim2.new(0.9, 0, 0, 25)
tokenLabel.BackgroundTransparency = 1
tokenLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
tokenLabel.TextXAlignment = Enum.TextXAlignment.Left
tokenLabel.Text = "GitHub Personal Access Token (PAT):"
tokenLabel.Parent = settingsGui

local tokenBox = Instance.new("TextBox")
tokenBox.Size = UDim2.new(0.9, 0, 0, 35)
tokenBox.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
tokenBox.TextColor3 = Color3.fromRGB(255, 255, 255)
tokenBox.TextSize = 14
tokenBox.ClearTextOnFocus = false
tokenBox.Text = Config.GetToken(pluginInstance)
tokenBox.Parent = settingsGui

local repoLabel = Instance.new("TextLabel")
repoLabel.Size = UDim2.new(0.9, 0, 0, 25)
repoLabel.BackgroundTransparency = 1
repoLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
repoLabel.TextXAlignment = Enum.TextXAlignment.Left
repoLabel.Text = "Repository (owner/repo):"
repoLabel.Parent = settingsGui

local repoBox = Instance.new("TextBox")
repoBox.Size = UDim2.new(0.9, 0, 0, 35)
repoBox.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
repoBox.TextColor3 = Color3.fromRGB(255, 255, 255)
repoBox.TextSize = 14
repoBox.ClearTextOnFocus = false
repoBox.Text = Config.GetRepo(pluginInstance)
repoBox.Parent = settingsGui

local saveButton = Instance.new("TextButton")
saveButton.Size = UDim2.new(0.9, 0, 0, 35)
saveButton.BackgroundColor3 = Color3.fromRGB(0, 162, 255)
saveButton.TextColor3 = Color3.fromRGB(255, 255, 255)
saveButton.TextSize = 16
saveButton.Font = Enum.Font.SourceSansBold
saveButton.Text = "Save Settings"
saveButton.Parent = settingsGui

saveButton.MouseButton1Click:Connect(function()
    Config.SetToken(pluginInstance, tokenBox.Text)
    Config.SetRepo(pluginInstance, repoBox.Text)
    saveButton.Text = "Saved!"
    print("[GitHubSync] Settings saved successfully.")
    task.wait(1.5)
    saveButton.Text = "Save Settings"
end)

-- Repository Viewer GUI
local viewerGui = Instance.new("Frame")
viewerGui.Size = UDim2.new(1, 0, 1, 0)
viewerGui.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
viewerGui.Parent = viewerWidget

local viewerTopBar = Instance.new("Frame")
viewerTopBar.Size = UDim2.new(1, 0, 0, 40)
viewerTopBar.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
viewerTopBar.BorderSizePixel = 0
viewerTopBar.Parent = viewerGui

local refreshButton = Instance.new("TextButton")
refreshButton.Size = UDim2.new(0, 120, 0, 30)
refreshButton.Position = UDim2.new(0, 10, 0, 5)
refreshButton.BackgroundColor3 = Color3.fromRGB(0, 162, 255)
refreshButton.TextColor3 = Color3.fromRGB(255, 255, 255)
refreshButton.Font = Enum.Font.SourceSansBold
refreshButton.TextSize = 14
refreshButton.Text = "Refresh Viewer"
refreshButton.Parent = viewerTopBar

local statusLabel = Instance.new("TextLabel")
statusLabel.Size = UDim2.new(1, -140, 1, 0)
statusLabel.Position = UDim2.new(0, 140, 0, 0)
statusLabel.BackgroundTransparency = 1
statusLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
statusLabel.TextSize = 14
statusLabel.TextXAlignment = Enum.TextXAlignment.Left
statusLabel.Text = "Click Refresh to load repository files."
statusLabel.Parent = viewerTopBar

local scrollingFrame = Instance.new("ScrollingFrame")
scrollingFrame.Size = UDim2.new(1, 0, 1, -40)
scrollingFrame.Position = UDim2.new(0, 0, 0, 40)
scrollingFrame.BackgroundTransparency = 1
scrollingFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
scrollingFrame.AutomaticCanvasSize = Enum.AutomaticSize.Y
scrollingFrame.Parent = viewerGui

local scrollerLayout = Instance.new("UIListLayout")
scrollerLayout.Padding = UDim.new(0, 4)
scrollerLayout.Parent = scrollingFrame

local function refreshViewer()
    local token = Config.GetToken(pluginInstance)
    local repo = Config.GetRepo(pluginInstance)
    if token == "" or repo == "" then
        local err = "Error: Token or Repository not configured in Settings."
        statusLabel.Text = err
        warn("[GitHubSync Error] " .. err)
        return
    end
    
    statusLabel.Text = "Fetching repository tree..."
    for _, child in ipairs(scrollingFrame:GetChildren()) do
        if child:IsA("TextLabel") then
            child:Destroy()
        end
    end
    
    local successBranch, branchOrErr = GitHubAPI.GetDefaultBranch(token, repo)
    local branch = successBranch and branchOrErr or "main"
    
    local successTree, treeData = GitHubAPI.GetRepoTree(token, repo, branch)
    if not successTree or not treeData or not treeData.tree then
        local err = "Failed to fetch tree: " .. tostring(treeData)
        statusLabel.Text = err
        warn("[GitHubSync Error] " .. err)
        return
    end
    
    local count = 0
    for _, node in ipairs(treeData.tree) do
        if node.type == "blob" then
            count = count + 1
            local itemLabel = Instance.new("TextLabel")
            itemLabel.Size = UDim2.new(1, -20, 0, 24)
            itemLabel.BackgroundTransparency = 1
            itemLabel.TextColor3 = Color3.fromRGB(220, 220, 220)
            itemLabel.TextSize = 13
            itemLabel.TextXAlignment = Enum.TextXAlignment.Left
            itemLabel.Text = "  " .. node.path
            itemLabel.Parent = scrollingFrame
        end
    end
    
    statusLabel.Text = string.format("Loaded %d file(s) from branch '%s'.", count, branch)
    print(string.format("[GitHubSync] Viewer loaded %d files from repository %s.", count, repo))
end

refreshButton.MouseButton1Click:Connect(refreshViewer)

settingsButton.Click:Connect(function()
    settingsWidget.Enabled = not settingsWidget.Enabled
end)

viewerButton.Click:Connect(function()
    viewerWidget.Enabled = not viewerWidget.Enabled
    if viewerWidget.Enabled then
        refreshViewer()
    end
end)

pushButton.Click:Connect(function()
    local token = Config.GetToken(pluginInstance)
    local repo = Config.GetRepo(pluginInstance)
    
    print("[GitHubSync] Pushing to GitHub...")
    local success, message = SyncManager.Push(token, repo)
    print("[GitHubSync]", message)
    
    if success then
        pushButton.SetActive(true)
        task.delay(2, function()
            pushButton.SetActive(false)
        end)
    else
        pushButton.SetActive(false)
    end
end)

pullButton.Click:Connect(function()
    local token = Config.GetToken(pluginInstance)
    local repo = Config.GetRepo(pluginInstance)
    
    print("[GitHubSync] Pulling from GitHub...")
    local success, message = SyncManager.Pull(token, repo)
    print("[GitHubSync]", message)
end)

print("[GitHubSync] Plugin initialized successfully (Single-File version).")
