local Serializer = {}

-- Adds metadata comment to script source for GitHub
function Serializer.Serialize(scriptInstance)
    local className = scriptInstance.ClassName
    if className ~= "Script" and className ~= "LocalScript" and className ~= "ModuleScript" then
        return nil, "Invalid script type"
    end
    
    local source = scriptInstance.Source or ""
    local header = string.format("-- @ScriptType: %s\n-- @ClassName: %s\n-- Generated by Roblox GitHub Sync Plugin\n\n", className, className)
    
    return header .. source, className
end

-- Parses metadata comment from GitHub file content and returns (scriptType, cleanSource)
function Serializer.Deserialize(content)
    if not content then return "Script", "" end
    
    local scriptType = "Script"
    local lines = string.split(content, "\n")
    local lineIndex = 1
    
    -- Parse up to first 5 lines for metadata
    while lineIndex <= math.min(5, #lines) do
        local line = lines[lineIndex]
        if line:match("^%s*-%-%s*@ScriptType:%s*(%w+)") then
            scriptType = line:match("^%s*-%-%s*@ScriptType:%s*(%w+)")
        end
        if line:match("^%s*-%-%s*@") then
            lineIndex = lineIndex + 1
        else
            break
        end
    end
    
    -- Skip trailing empty lines right after metadata
    while lineIndex <= #lines and lines[lineIndex]:match("^%s*$") do
        lineIndex = lineIndex + 1
    end
    
    local cleanLines = {}
    for i = lineIndex, #lines do
        table.insert(cleanLines, lines[i])
    end
    
    local cleanSource = table.concat(cleanLines, "\n")
    return scriptType, cleanSource
end

return Serializer
